--Creates the uuid functions we need in our schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--Create stock table with autogenerated uuid for the stock id
--This is our root table which holds company data for each stock we plan on tracking
create table avg_inv.stocks (
	stock_id uuid default uuid_generate_v4 (),
	ticker_symbol varchar(5) not null,
	company varchar(150) not null,
	market varchar(150) not null,
	primary key (stock_id)
);